### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by chipsh** [decile-team/distil#29]
Hello authors,
It's great that you publish the source code, but the default hyper-parameters in _**config_cifar10_resnet_badge.json**_ can not get similar accuracy in your project about badge strategy, so could you please share the hyper-params to produce the graph in README.

**Comment by ApurvaDani** [comment]
To reproduce the results, we have provided notebooks in neurips_notebooks folder.
For the experiment you are performing, you should use the notebook at neurips_notebooks/Baseline/AL_CIFAR10_Baseline_Master_NeurIPS.ipynb.
This notebooks has all the active learning strategies, you can choose to run the BADGE cell after executing the initial few cells.

**Comment by nab170130** [comment]
For consistency, I have updated the configuration files with the parameters used in the experiments that produced the figures in the README. Using train.py with these configurations should now produce similar results.
