### ISSUE TITLE
Add SIM Based AL strategy using the SMI functions from submodlib

### ISSUE THREAD

**Issue by rishabhk108** [decile-team/distil#32]
- SMI based AL (using query set)
- CSMI based AL (using a query + conditioning set)
- CG Based AL (using a conditioning set)

**Comment by surajkothawade** [comment]
Can be resolved after merging PR #41

**Comment by nab170130** [comment]
This issue has been resolved by the latest merge to main. There are now three strategies - SCG, SCMI, and SMI - that solve the targeted AL problem via submodular optimization from submodlib.
